#
# (C) Copyright 2017 DSPG Group
#
# See file CREDITS for list of people who contributed to this
# project.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307 USA
#

ccflags-$(CONFIG_RTL8363NB_SWITCH) += -DMDC_MDIO_OPERATION -D_LITTLE_ENDIAN
ccflags-$(CONFIG_RTL8363NB_SWITCH) += -I../../external/drivers/rtl8363nb/uboot/include

obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8363nb.o
obj-$(CONFIG_RTL8363NB_SWITCH) += acl.o
obj-$(CONFIG_RTL8363NB_SWITCH) += cpu.o
obj-$(CONFIG_RTL8363NB_SWITCH) += dot1x.o
obj-$(CONFIG_RTL8363NB_SWITCH) += eee.o
obj-$(CONFIG_RTL8363NB_SWITCH) += igmp.o
obj-$(CONFIG_RTL8363NB_SWITCH) += interrupt.o
obj-$(CONFIG_RTL8363NB_SWITCH) += l2.o
obj-$(CONFIG_RTL8363NB_SWITCH) += leaky.o
obj-$(CONFIG_RTL8363NB_SWITCH) += led.o
obj-$(CONFIG_RTL8363NB_SWITCH) += mirror.o
obj-$(CONFIG_RTL8363NB_SWITCH) += oam.o
obj-$(CONFIG_RTL8363NB_SWITCH) += port.o
obj-$(CONFIG_RTL8363NB_SWITCH) += ptp.o
obj-$(CONFIG_RTL8363NB_SWITCH) += qos.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rate.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rldp.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtk_switch.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_acl.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_cputag.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_dot1x.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_eav.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_eee.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_fc.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_green.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_hsb.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_igmp.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_inbwctrl.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_interrupt.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_led.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_lut.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_meter.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_mib.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_mirror.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_misc.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_oam.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_phy.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_port.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_portIsolation.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_qos.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_rldp.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_rma.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_scheduling.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_storm.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_svlan.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_trunking.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_unknownMulticast.o
obj-$(CONFIG_RTL8363NB_SWITCH) += rtl8367c_asicdrv_vlan.o
obj-$(CONFIG_RTL8363NB_SWITCH) += smi.o
obj-$(CONFIG_RTL8363NB_SWITCH) += stat.o
obj-$(CONFIG_RTL8363NB_SWITCH) += storm.o
obj-$(CONFIG_RTL8363NB_SWITCH) += svlan.o
obj-$(CONFIG_RTL8363NB_SWITCH) += trap.o
obj-$(CONFIG_RTL8363NB_SWITCH) += trunk.o
obj-$(CONFIG_RTL8363NB_SWITCH) += vlan.o
